// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Cube_78fdd04f22ed43f40bf52f012fa8bf3bIndex = 0;
		public const int GameManager_a100b647a956c8a46a8a62809195868dIndex = 1;
		public const int GameManager__char_32_1_979025f5a787e6a43b86dc71f2bf290bIndex = 2;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Cube_78fdd04f22ed43f40bf52f012fa8bf3b", 0 },

			{ "GameManager_a100b647a956c8a46a8a62809195868d", 1 },

			{ "GameManager__char_32_1_979025f5a787e6a43b86dc71f2bf290b", 2 },

		};
	}
}
