// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Cube_78fdd04f22ed43f40bf52f012fa8bf3bIndex = 0;
		public const int NetworkSync_3be44a6dcf9a3d940bf4c430edc35dfcIndex = 1;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Cube_78fdd04f22ed43f40bf52f012fa8bf3b", 0 },

			{ "NetworkSync_3be44a6dcf9a3d940bf4c430edc35dfc", 1 },

		};
	}
}
