// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct WorldPosition : ICoherenceComponentData
	{
		public Vector3 value;

		public override string ToString()
		{
			return $"WorldPosition(value: {value})";
		}

		public uint GetComponentType() => Definition.InternalWorldPosition;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (WorldPosition)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				value = other.value;
			}
			mask >>= 1;
			return this;
		}

		public static void Serialize(WorldPosition data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteVector3((data.value.ToCoreVector3()), FloatMeta.NoCompression());
			}
			mask >>= 1;
		}

		public static (WorldPosition, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
	
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}
			return (val, mask, null);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeNewTIle_04b6d49a234671740be9111d88a3c8dd_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32___char_45_1__char_32_2_b5d8024812dce5541be176fc1f4abfac_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32___char_45_2__char_32_3_51469b0c4ef704d42b70f82e661b0b19_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32___char_45_3__char_32_4_c6a10a1063e6c8349b57189e249d9c5d_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32___char_45_4__char_32_5_abb3dd103be1a384e9918dcb46579d18_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32___char_45_5__char_32_6_f84aec38edf04a74e948fcb478268d00_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32___char_45_6__char_32_7_7a6c362c74de39048ac54d13e3bb400f_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32_0__char_32_1_5dbe1d5e0551b4a46ab9c5dd95df68d8_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32_1__char_32_0_ee2cf82f8603cf14e8934c06a873f465_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32_2__char_32___char_45_1_f98d074c7c655da41b95ad619d1aaae2_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32_3__char_32___char_45_2_91024cb7f58ba034da1a86cbced33aa5_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32_4__char_32___char_45_3_cc95c0ee90b5e4348afa3b22491ac1e2_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32_5__char_32___char_45_4_c750001c71cba89449e1bf9c315e9b61_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32_6__char_32___char_45_5_5806e83f3b4fa734485fd6bb08f66c50_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_1__char_32_7__char_32___char_45_6_5c8af66bec027014997f05baea872372_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32___char_45_1__char_32_3_999d7797693c47a468d3a65c51af8f03_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32___char_45_2__char_32_4_b5078e09aa2e928488789fdf1324e536_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32___char_45_3__char_32_5_f0de473d25f230d4e834b77ba96d6ea9_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32___char_45_4__char_32_6_229715f1d4b99b544b9d2b0f37e97562_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32___char_45_5__char_32_7_d689c5d100c5ce542858e3125b60fe37_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32_0__char_32_2_401bc43f20b3baf4482d02e641877b42_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32_1__char_32_1_d65caddb280aa2c4cb68ab9bd293b605_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32_2__char_32_0_95e78d9285010ac4db2604b82ccf92d4_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32_3__char_32___char_45_1_3b10aff23f2de0e448830ee9eea552d1_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32_4__char_32___char_45_2_f8bc680ba7ec32047ba2aea96447f759_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32_5__char_32___char_45_3_53d853bbc2f400140b5838ee3d66a232_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32_6__char_32___char_45_4_c7b48850b1ffef743b357fb08f87acdf_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_2__char_32_7__char_32___char_45_5_0610b2bc97b65da4cae9549d98419c2b_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_3__char_32___char_45_1__char_32_4_bdaa82f9969908b4496c413712f37b62_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_3__char_32___char_45_2__char_32_5_ae7bf241067559f4aa43fc5a2c13f59f_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_3__char_32___char_45_3__char_32_6_1e0339686382e8e46ac29a58655c39e3_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_3__char_32___char_45_4__char_32_7_260d9840341219f4898bd247d773ecf5_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_3__char_32_0__char_32_3_412c41043b429464ea9ed23c867dd425_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_3__char_32_1__char_32_2_d06e8dddb2d951345afb5ea362555635_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_3__char_32_2__char_32_1_15e0f4a589c398d46a51ab2fdd357c20_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_3__char_32_3__char_32_0_c8d90e0222def8d449cb4ed6874859b7_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_3__char_32_4__char_32___char_45_1_db32d90a8eb14b24cab373b1ceccaa4a_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_3__char_32_5__char_32___char_45_2_54284e94b1dabcd42870de0422bec66a_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_3__char_32_6__char_32___char_45_3_0b2dbfbade7331d49b1da3d59bec5795_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_3__char_32_7__char_32___char_45_4_ce3c9d4458599704f83ee79ec5766a04_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_4__char_32___char_45_1__char_32_5_88107bd103968ec409fbd1a10163a7e5_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_4__char_32___char_45_2__char_32_6_aa72522ee5b8a274f929c298e0c1169e_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_4__char_32___char_45_3__char_32_7_39bcd8a1c28d1884eaae61fa844ea483_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_4__char_32_0__char_32_4_14ad629e610026c4c81af81e73635f55_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_4__char_32_1__char_32_3_6c466ac09e1b35c40b7f06a568dbb13b_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_4__char_32_2__char_32_2_5bfd21978ab2b0345ab8e8acf58727eb_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_4__char_32_3__char_32_1_bac1d419117ab75479f03df5d8e2c749_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_4__char_32_4__char_32_0_9dad4b1e1f250434b8de13a8e5bcf5b5_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_4__char_32_5__char_32___char_45_1_6062d6b72c9324f4c88a5d84172ca426_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_4__char_32_6__char_32___char_45_2_0bd8d5497f3b1ca42ada89b52a9c199f_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_4__char_32_7__char_32___char_45_3_c0d5346fd864dc64782c13982aa7452e_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_5__char_32___char_45_1__char_32_6_076763852e9737f40827d99c0779c577_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_5__char_32___char_45_2__char_32_7_a1bdcfc15046ebc40921c73b8955e593_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_5__char_32_0__char_32_5_e71aa74d2ddc8b5479314cb30c869698_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_5__char_32_1__char_32_4_609e86bdbfad6c74c9fc05280213a04a_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_5__char_32_2__char_32_3_42e811dcf455588428ecd7be58798acf_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_5__char_32_3__char_32_2_2166455582ddd54458a4c4155306375e_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_5__char_32_4__char_32_1_8f05e8d3e4341a34f9fda1f77612bfcd_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_5__char_32_5__char_32_0_e25cbb99e8f4fac45920b1ae25b35cfd_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_5__char_32_6__char_32___char_45_1_3e90bbfe00f6c644eaaaf0401cd999a3_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_5__char_32_7__char_32___char_45_2_4e789bdca745b444892df985d3884e84_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_6__char_32___char_45_1__char_32_7_7d0d57bfb78f03549a4369f56708cbd8_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_6__char_32_0__char_32_6_a4938a5110cdbdc4d9614b8156f30a34_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_6__char_32_1__char_32_5_d713c281f15949446accd255b3d2c593_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_6__char_32_2__char_32_4_dd0198ba0f57000469000636d3c859bb_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_6__char_32_3__char_32_3_be0c5afe323bf954ea74493016c31510_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_6__char_32_4__char_32_2_85dfd07e4b920b5438401d9484456cd9_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_6__char_32_5__char_32_1_0d24a2391a8dbb94ba9d6b0e4bd7cb47_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_6__char_32_6__char_32_0_fecf3773e8ad2b34da9262e7be9a314f_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_6__char_32_7__char_32___char_45_1_442fe557e2631d44cba376c1fd5c746d_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_7__char_32_0__char_32_7_5f638fec11c56f942a52989600fc4e95_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_7__char_32_1__char_32_6_652eb33c671f33641b20ada4659b4677_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_7__char_32_2__char_32_5_2d1d1115d1fb2a641801c5dacee2c236_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_7__char_32_3__char_32_4_26a68df44cc2bf048888783e9d3fec7b_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_7__char_32_4__char_32_3_56e5a4721715c044c82b38fd01dcbc0a_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_7__char_32_5__char_32_2_3646281bd82395a42b05f22e1dcf4737_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_7__char_32_6__char_32_1_0e1cd6647c4e4684787acc6b02ee8bd1_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32___char_45_7__char_32_7__char_32_0_589b1ecfa5a8dfa4b9c9a507d80c61db_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32___char_45_1__char_32_1_6e0e488dce3af7f43816c97affcdaf29_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32___char_45_2__char_32_2_34b2e6350c64b7449b606ab0d6c28dc7_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32___char_45_3__char_32_3_37c51cadb3846734da6ad005fc4f0356_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32___char_45_4__char_32_4_2568eab43e27f3a43b02987eb0c664b7_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32___char_45_5__char_32_5_1abe35d7f8862064282267bed2c48461_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32___char_45_6__char_32_6_efe41accc1bd5ef41b41f96fa8426403_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32___char_45_7__char_32_7_8d8fde235b7289f40945904500cf17c9_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32_0__char_32_0_d21a43a71dd4df54383c75501f7269e1_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32_1__char_32___char_45_1_70e4f8fa48ac8a34083baf4c4c86df43_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32_2__char_32___char_45_2_6f287be3a8449b643aea16eba15cfab3_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32_3__char_32___char_45_3_e378ad8fcf7c5754bbff6c781f0c99cb_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32_4__char_32___char_45_4_84107baa655481948b1fb9cf50952acc_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32_5__char_32___char_45_5_49680eb4451c03847bcdc12c4775eb01_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32_6__char_32___char_45_6_ba7203e7af173584bab15d5252cfd604_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_0__char_32_7__char_32___char_45_7_fe309824efe8da44a9170140bf1517de_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32___char_45_1__char_32_0_d1ff3225212ef924289d9921b56f717d_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32___char_45_2__char_32_1_4bcb6a2c91a5f6846a36f7ed60c90f13_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32___char_45_3__char_32_2_9aff72005601c594c8221ce9147718ce_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32___char_45_4__char_32_3_992a931c9ebfbf14d854ef0d9393635f_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32___char_45_5__char_32_4_d2246dcfeba1e11418e863f296b713db_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32___char_45_6__char_32_5_7134577a1a9dee349bc79b735549ddc8_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32___char_45_7__char_32_6_a53a4985a07f55f40b658a8dac9ae959_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32_0__char_32___char_45_1_f729b56743f163b49a2d5e815e116b02_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32_1__char_32___char_45_2_f948ab3b2f242514990a4113a7acd2c7_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32_2__char_32___char_45_3_8a32b97311eb39f48a0ce7ebd7fd018c_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32_3__char_32___char_45_4_0e4eab416608f6d4db3c59ad894bc903_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32_4__char_32___char_45_5_f0ed17712b84b1e4ea1e07064d2cc662_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32_5__char_32___char_45_6_bbbe01783e2fd3e4fa23b7d84bbdfc48_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_1__char_32_6__char_32___char_45_7_57b797d30ee72a54eb132abdeb1f1dbc_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32___char_45_1__char_32___char_45_1_9b2be37ed333d774d87ac377761dd3de_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32___char_45_2__char_32_0_2a0f4854e53c18a4497580453913319d_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32___char_45_3__char_32_1_862abf9c4812cf54d8b92b2386085472_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32___char_45_4__char_32_2_0c8f1e2ac0ea02f43b1bbb629721e391_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32___char_45_5__char_32_3_c3e67a2e9ed15a84584271959aea2244_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32___char_45_6__char_32_4_f9c0b30c209ec114bb233776cb754088_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32___char_45_7__char_32_5_26c6fd14094a9234f8ab3ee0ee40e463_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32_0__char_32___char_45_2_4192aa74537eda542b32cfe743b9fadb_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32_1__char_32___char_45_3_3fd8b0e23afa7454baf3d77e4c1d412e_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32_2__char_32___char_45_4_f3aa466ceed26f7408eca309b17ddfad_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32_3__char_32___char_45_5_eea3357534408754f9c4a9e1e7ec32ee_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32_4__char_32___char_45_6_8830b0c389208a047b486c0ce3ddaed5_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_2__char_32_5__char_32___char_45_7_c12d3d692d42dd4418e0b0dd0a65b5bd_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_3__char_32___char_45_1__char_32___char_45_2_9df63994ec22d8e4d9244b6d8da0c8b9_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_3__char_32___char_45_2__char_32___char_45_1_81da6c65719d5a94a8766a82b9715f00_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_3__char_32___char_45_3__char_32_0_9faf2d72c4fd0fe45b34c22a4089131d_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_3__char_32___char_45_4__char_32_1_6e119bdfd1e6d4144aa4925ab5286bf4_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_3__char_32___char_45_5__char_32_2_7bf94d1c70e701145a03595087672dae_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_3__char_32___char_45_6__char_32_3_389262df581524546a58f78cce3cac89_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_3__char_32___char_45_7__char_32_4_d6d6d88ff4d9ad94eaad3b10d93f0df8_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_3__char_32_0__char_32___char_45_3_ccc76b8f9eca10f468760230d2fef2da_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_3__char_32_1__char_32___char_45_4_a11f6d2847533a14bbce3e77cf1616f0_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_3__char_32_2__char_32___char_45_5_ba132444a895eff49b69ccef7b961b1b_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_3__char_32_3__char_32___char_45_6_f1056336734e0a541a611f40a3b0a44f_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_3__char_32_4__char_32___char_45_7_05e3a1a8a14f0e74e8cb88c23a85cc69_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_4__char_32___char_45_1__char_32___char_45_3_75d038249441cd14a8d238195b5634b7_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_4__char_32___char_45_2__char_32___char_45_2_d632fec231639fc42bfa156fc09de7c2_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_4__char_32___char_45_3__char_32___char_45_1_840ebea9ea8f13a4c90f273149f25930_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_4__char_32___char_45_4__char_32_0_4736ca94ac0dd0544bb144d64964692a_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_4__char_32___char_45_5__char_32_1_07b9941b5feec3e4a8dc1ec371a0993c_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_4__char_32___char_45_6__char_32_2_fd54bce1004c59a4292c896dcf756f6b_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_4__char_32___char_45_7__char_32_3_65d52ebd1c85d5646a4b2ddf6eec2b0d_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_4__char_32_0__char_32___char_45_4_1159990ec3f62c649b45b6e30dd5dfca_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_4__char_32_1__char_32___char_45_5_07a410cc91fd2a94e9f571bb06956da5_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_4__char_32_2__char_32___char_45_6_90f442d78df717e468caa4b6992ebf01_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_4__char_32_3__char_32___char_45_7_673cc743d121bc04cbfde897925ae919_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_5__char_32___char_45_1__char_32___char_45_4_05a7989164fa0c243a0579d047f1aebf_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_5__char_32___char_45_2__char_32___char_45_3_058e8789a64ddda4b8ac51ccb3cc77f7_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_5__char_32___char_45_3__char_32___char_45_2_41a2c4e3aabdf214c8d01baa48423686_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_5__char_32___char_45_4__char_32___char_45_1_bc3e21ce9646d1943895154236735953_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_5__char_32___char_45_5__char_32_0_7f1833d3d0b0cb3468896dab9f32ee07_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_5__char_32___char_45_6__char_32_1_f8bbc40a7a07222448394209eea3b980_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_5__char_32___char_45_7__char_32_2_13a239657a8f7454db471e410f15acc6_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_5__char_32_0__char_32___char_45_5_1aaa78154b946e440afdb1447e261bb9_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_5__char_32_1__char_32___char_45_6_ff4acd64f99eead49974dac1e38b8c3e_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_5__char_32_2__char_32___char_45_7_f672bdb77d9124249b38084603369f04_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_6__char_32___char_45_1__char_32___char_45_5_71a619b96a6c138478b95ba47177ded8_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_6__char_32___char_45_2__char_32___char_45_4_6e9c38742eb72264c9ac665f7777773c_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_6__char_32___char_45_3__char_32___char_45_3_1e20db9bda573384c819161a10b2e8a9_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_6__char_32___char_45_4__char_32___char_45_2_1dfe88c3d32bd0449bd378addaa37b40_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_6__char_32___char_45_5__char_32___char_45_1_81ffcd2c93d7a0344ab5246df710485c_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_6__char_32___char_45_6__char_32_0_85248359e730fb3449b37a1fb2ceb2b5_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_6__char_32___char_45_7__char_32_1_da5e9f9465dda3d42bb65aa3bfb2aee6_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_6__char_32_0__char_32___char_45_6_64c625d3536429642907a7f18df26eea_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_6__char_32_1__char_32___char_45_7_da1dc44130862694cad6b59cabe6a6fd_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_7__char_32___char_45_1__char_32___char_45_6_7ed0271739f38c84ea55f88d7badf39f_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_7__char_32___char_45_2__char_32___char_45_5_ea090bb31729cda40bdb905fac8df5c4_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_7__char_32___char_45_3__char_32___char_45_4_fa03ef50e6e7cbd47bb7958b2f376933_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_7__char_32___char_45_4__char_32___char_45_3_043afd664871b914f80180cb747c477b_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_7__char_32___char_45_5__char_32___char_45_2_3ccf41870098fe54e8241a57706ff8e7_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_7__char_32___char_45_6__char_32___char_45_1_627ad617c250ef74799e80067e2a4b77_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_7__char_32___char_45_7__char_32_0_fe5b245989d088f4c9528c76b6aa90c1_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (WorldPosition, uint, uint?) DeserializeArchetypeTile__char_32___char_45____char_32_7__char_32_0__char_32___char_45_7_c8ad030e92bf313439f07631c32c71c0_WorldPosition_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new WorldPosition();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as WorldPosition?;
	
		}
	}
}